name: Ping Servers via Ansible

on:
  workflow_dispatch:

jobs:
  ping:
    runs-on: self-hosted

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Run Ansible Ping
      run: |
        ansible-playbook -i inventory.yml ping.yml

