name: Ping Servers via Ansible

on:
  #workflow_dispatch:
  push:
    branches:
      - main # Change to your default branch if different

jobs:
  ping:
    runs-on: ansible-controller

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Run Ansible Ping
      run: |
        ansible-playbook -i inventory.yml ping.yml

