name: Ping All the VMs listed in the inventory via Ansible playbook

on:
  #workflow_dispatch:
  push:
    branches:
      - main # Change to your default branch if different

jobs:
  ping:
    runs-on: self-hosted

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Run Ansible Ping
      run: |
        #ansible-playbook -i inventory.yml ping.yml
        #ansible-playbook -i inventory.yml hosts-details.yml
        ansible-playbook -i inventory.yml see-pipeline.yml

